[strip-0]
limit = 12
label = ""

[strip-1]
A1 = true
A2 = true
A3 = true
B1 = true
B2 = true
mono = true
solo = true
mute = true
limit = 12
label = ""

[strip-2]
limit = 12
label = ""

[strip-3]
limit = 12
label = ""

[strip-4]
A1 = false
A2 = false
A3 = false
B1 = false
B2 = false
k = false
solo = false
mute = false
limit = 12
label = ""
